### ISSUE TITLE
Can't create presets

### ISSUE THREAD

**Issue by nickberckley** [schroef/Save-Render-Presets#2]
Python: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Save-Render-Presets-master\cycles_presets.py", line 130, in execute
    preset_path = bpy.utils.user_resource('SCRIPTS',target_path,create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

**Comment by schroef** [comment]
Okay, i think it should be fixed with the [new release ](https://github.com/schroef/Save-Render-Presets/releases/tag/v0.0.6)
Please note, ive not tested this in 3.4 yet. At work i only have 2.83 and cant go any higher with the old machine. I fixed it basically of what i could find in the API. It still works in older versions as well
